import JSZip from 'jszip';
import type { Plan, Project } from '@/generated/prisma/client';

export function buildProjectZip(project: Project, plan: Plan): JSZip {
  const zip = new JSZip();
  const name = project.name || 'project';

  // README.md
  zip.file(
    'README.md',
    `# ${name}\n\n${project.description || 'No description provided.'}\n\n## Getting Started\n\nThis project plan was generated by [init-ai](https://github.com/init-ai). Use it with your favorite AI coding tool (AntiGravity, Copilot, Cursor, OpenCode, etc.).\n\n## Project Structure\n\n- \`PRD.md\` — Product Requirements Document\n- \`task.md\` — Implementation task checklist\n- \`prompt_context.txt\` — Bootstrap context for AI tools\n- \`docs/\` — Architecture, API spec, database schema, workflow, diagrams, effort estimate\n\n> **Note:** This bundle also includes agent configuration files (\`.cursorrules\`, \`.agent/\`, \`.github/copilot-instructions.md\`) for your local AI tools. These are excluded from version control via \`.gitignore\` — they stay on your machine only.\n`
  );

  // PRD.md
  if (plan.prd) {
    zip.file('PRD.md', plan.prd);
  }

  // task.md
  if (plan.taskList) {
    zip.file('task.md', plan.taskList);
  }

  // prompt_context.txt
  if (plan.promptContext) {
    zip.file('prompt_context.txt', plan.promptContext);
  }

  // .cursorrules
  if (plan.rules) {
    zip.file('.cursorrules', plan.rules);
  }

  // .github/copilot-instructions.md
  if (plan.rules) {
    zip.file(
      '.github/copilot-instructions.md',
      `# Copilot Instructions\n\n${plan.rules}`
    );
  }

  // .agent/rules.md
  if (plan.rules) {
    zip.file('.agent/rules.md', plan.rules);
  }

  // docs/
  const docs = zip.folder('docs')!;

  if (plan.architecture) {
    docs.file('architecture.md', plan.architecture);
  }

  if (plan.apiSpec) {
    docs.file('api_spec.md', plan.apiSpec);
  }

  if (plan.dbSchema) {
    docs.file('database_schema.md', plan.dbSchema);
  }

  if (plan.workflow) {
    docs.file('workflow.md', plan.workflow);
  }

  if (plan.diagrams) {
    docs.file('diagrams.md', plan.diagrams);
  }

  if (plan.effortEstimate) {
    docs.file('effort_estimate.md', plan.effortEstimate);
  }

  // .init-ai/project.json (machine-readable metadata for re-import)
  const metadata = {
    id: project.id,
    name: project.name,
    description: project.description,
    status: project.status,
    planVersion: plan.version,
    exportedAt: new Date().toISOString(),
    generator: 'init-ai',
  };
  zip.file('.init-ai/project.json', JSON.stringify(metadata, null, 2));

  // .gitignore — hide vibe-coding config files from public VCS
  zip.file(
    '.gitignore',
    `# init-ai — vibe-coding config (hidden from public VCS)
.cursorrules
.agent/
.init-ai/
.github/copilot-instructions.md

# Common ignores
node_modules/
.env
.env.local
dist/
build/
.next/
`
  );

  return zip;
}
